$axure.loadCurrentPage({
  "url":"名帖2.html",
  "generationDate":new Date(1467728910639.43),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d0bff71f84e749e2a4b49274fb13324e",
    "type":"Axure:Page",
    "name":"名帖2",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"bdf366a7f5d7473c9b10155b7b562eac",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":126,
              "y":10},
            "size":{
              "width":424,
              "height":848},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8862dc975764470abbc968312dbb9331",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":126,
                  "y":10},
                "size":{
                  "width":424,
                  "height":848},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/名帖1/u0.png"}},
{
          "id":"ec1b42f6259948a697297832fd9ac137",
          "label":"",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":151,
              "y":99},
            "size":{
              "width":375,
              "height":667}},
          "adaptiveStyles":{
},
          "target":{
            "targetType":"webUrl",
            "urlLiteral":{
              "exprType":"stringLiteral",
              "value":"",
              "stos":[]},
            "includeVariables":false}},
{
          "id":"00a15c22eaae4289bd4d4607499bc050",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":189,
              "y":291},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6092e0296eab4c1296e4af397993a64f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":189,
                  "y":291},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/名帖2/u3.png"}},
{
          "id":"5fda81017f5b4e77aede2b8641bfa86b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":237,
              "y":302},
            "size":{
              "width":145,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e42f8bb3386b4764be0c0c034b52de93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":237,
                  "y":302},
                "size":{
                  "width":145,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b139b0d2a0db4d1ba8fc36f4932ea123",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":415,
              "y":302},
            "size":{
              "width":58,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fdd5ccaeabe246fa8889dd7d9c4ac8c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":415,
                  "y":302},
                "size":{
                  "width":58,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/名帖2/u7.png"}},
{
          "id":"9be7c17d9efb45d19bafcbf130e3544b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":192,
              "y":498},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b7ca7dd7d134bfa806c95d5eac1ccc1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":192,
                  "y":498},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/名帖2/u3.png"}},
{
          "id":"97e9111bf32d41c49911d61c80015080",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":240,
              "y":514},
            "size":{
              "width":145,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa6abea2bca34f9e808a657e2f08a1c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":240,
                  "y":514},
                "size":{
                  "width":145,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a930fdd4abd74848aa8c8a2a1c8a7d2d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":418,
              "y":510},
            "size":{
              "width":58,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58621cd637954c1382c76b09b8f4a524",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":418,
                  "y":510},
                "size":{
                  "width":58,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/名帖2/u7.png"}},
{
          "id":"4ff4cb67dca54716a376556e5ea20960",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":192,
              "y":577},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"798967be86c04f91a254761557712211",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":192,
                  "y":577},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/名帖2/u3.png"}},
{
          "id":"4c23b325341c4ae485f478d92e2fdf33",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":240,
              "y":593},
            "size":{
              "width":145,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"321306a91ed148ca95e952220bd25999",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":240,
                  "y":593},
                "size":{
                  "width":145,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"56c0f46a4b5e4f949c11f9a8c69bb171",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":192,
              "y":651},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"712074d7da2a405189df9701e7fbfbf5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":192,
                  "y":651},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/名帖2/u3.png"}},
{
          "id":"5e0ce07fc0e84cff90a6f6742c3fcbe4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":240,
              "y":667},
            "size":{
              "width":145,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd6fa6a9cb684aae813ecee3b390e290",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":240,
                  "y":667},
                "size":{
                  "width":145,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f959ba222daa4e49aab64e67cc101e92",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":418,
              "y":665},
            "size":{
              "width":58,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c6555faffda4e66ae24d494151150b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":418,
                  "y":665},
                "size":{
                  "width":58,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/名帖2/u7.png"}},
{
          "id":"e2d95a4a11364b278cff6e2ad82042b1",
          "label":"time_panel",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":151,
              "y":99},
            "size":{
              "width":375,
              "height":20},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d084b3fc21e40c0be4e0934881e3a0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":151,
                  "y":99},
                "size":{
                  "width":375,
                  "height":20},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/名帖1/time_panel_u9.png"}},
{
          "id":"b6fffe6b87804661838b5bd86dea465d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'IOS8-Icons Regular', 'IOS8-Icons'",
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":189,
              "y":99},
            "size":{
              "width":22,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a408485f149e41de8a39182d487a0436",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'IOS8-Icons Regular', 'IOS8-Icons'",
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":189,
                  "y":99},
                "size":{
                  "width":22,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/名帖1/u11.png"}},
{
          "id":"14c367401ae04f73840d973857b67c95",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":156,
              "y":107},
            "size":{
              "width":33,
              "height":5}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58f3bdbcfd8544438ee73f49dd4e4f3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":156,
                  "y":107},
                "size":{
                  "width":33,
                  "height":5}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/名帖1/u13.png"}},
{
          "id":"3c56dc089e9a41f58e4ac5f7cddf243c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":491,
              "y":104},
            "size":{
              "width":25,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5827232483074b8995c3b2925f25f92d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":491,
                  "y":104},
                "size":{
                  "width":25,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/名帖1/u15.png"}},
{
          "id":"102c2e6ebbd44130a68775b7c765968d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":460,
              "y":101},
            "size":{
              "width":31,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a234f1680af418c8f662770fc927290",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":460,
                  "y":101},
                "size":{
                  "width":31,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/名帖1/u17.png"}},
{
          "id":"6013fefe84ea4f75bdcaadc437bc0789",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'IOS8-Icons Regular', 'IOS8-Icons'",
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":438,
              "y":99},
            "size":{
              "width":22,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d30cc8e0cdef4edeb001a83d4fb47829",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'IOS8-Icons Regular', 'IOS8-Icons'",
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":438,
                  "y":99},
                "size":{
                  "width":22,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/名帖1/u11.png"}},
{
          "id":"514bed839fff4383b77c9b9a6d5c7882",
          "label":"timer",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":301,
              "y":99},
            "size":{
              "width":18,
              "height":20}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onPanelStateChange":{
              "description":"OnPanelStateChange",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set text on time_panel equal to &quot;[['0'.concat(hours).slice(-...&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["7d084b3fc21e40c0be4e0934881e3a0a"]},
{
                                "exprType":"stringLiteral",
                                "value":"[['0'.concat(hours).slice(-2)]]:[['0'.concat(minutes).slice(-2)]]",
                                "localVariables":{
},
                                "stos":[{
                                    "computedType":"string",
                                    "sto":"fCall",
                                    "thisSTO":{
                                      "computedType":"string",
                                      "desiredType":"string",
                                      "sto":"fCall",
                                      "thisSTO":{
                                        "computedType":"string",
                                        "desiredType":"string",
                                        "sto":"literal",
                                        "value":"0"},
                                      "func":"concat",
                                      "arguments":[{
                                          "sto":"var",
                                          "name":"hours"}]},
                                    "func":"slice",
                                    "arguments":[{
                                        "computedType":"int",
                                        "sto":"unOp",
                                        "op":"-",
                                        "inputSTO":{
                                          "computedType":"int",
                                          "sto":"literal",
                                          "value":2}}]},
{
                                    "computedType":"string",
                                    "sto":"fCall",
                                    "thisSTO":{
                                      "computedType":"string",
                                      "desiredType":"string",
                                      "sto":"fCall",
                                      "thisSTO":{
                                        "computedType":"string",
                                        "desiredType":"string",
                                        "sto":"literal",
                                        "value":"0"},
                                      "func":"concat",
                                      "arguments":[{
                                          "sto":"var",
                                          "name":"minutes"}]},
                                    "func":"slice",
                                    "arguments":[{
                                        "computedType":"int",
                                        "sto":"unOp",
                                        "op":"-",
                                        "inputSTO":{
                                          "computedType":"int",
                                          "sto":"literal",
                                          "value":2}}]}]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]}]}}]}]},
            "onLoad":{
              "description":"OnLoad",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set timer to Next wrap repeat every 60000 ms",
                      "panelsToStates":[{
                          "panelPath":["514bed839fff4383b77c9b9a6d5c7882"],
                          "stateInfo":{
                            "setStateType":"next",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":true,
                            "showWhenSet":false,
                            "repeat":60000,
                            "options":{
                              "compress":false}}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"29ffc838d1324813b3a6f08ca561b371",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"bac0b3fd8c2a4dcebb9054334270c355",
              "label":"State2",
              "type":"Axure:PanelDiagram",
              "objects":[],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"31350cfcdb0b44f982b4e0c39360a44a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":267,
              "y":347},
            "size":{
              "width":143,
              "height":135}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48ee8c3754f64da8836891b680c85235",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":267,
                  "y":347},
                "size":{
                  "width":143,
                  "height":135}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/名帖2/u38.png"}},
{
          "id":"52b5a0c4d3e14c72a8017c4d56b0020b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":288,
              "y":482},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41e1d2a0712341058b4b5a433239d27c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":288,
                  "y":482},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f089b396ad6642ba892d0853c9c081dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":175,
              "y":156},
            "size":{
              "width":335,
              "height":112}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14f2bbb30f25483eb52ed6f8d38e8ced",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":175,
                  "y":156},
                "size":{
                  "width":335,
                  "height":112}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1002516d969f44c996fe69fc90013568",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":415,
              "y":596},
            "size":{
              "width":69,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"380e9a3d72ae47799ca561bcc56c9d03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":415,
                  "y":596},
                "size":{
                  "width":69,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"52ed4607524a43f1babd984c2431695f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":292,
              "y":701},
            "size":{
              "width":79,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a08437fc4cad4eaab7ce668a1faab5bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":292,
                  "y":701},
                "size":{
                  "width":79,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/名帖1/u22.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "bdf366a7f5d7473c9b10155b7b562eac":{
      "scriptId":"u0"},
    "8862dc975764470abbc968312dbb9331":{
      "scriptId":"u1"},
    "ec1b42f6259948a697297832fd9ac137":{
      "scriptId":"u2"},
    "00a15c22eaae4289bd4d4607499bc050":{
      "scriptId":"u3"},
    "6092e0296eab4c1296e4af397993a64f":{
      "scriptId":"u4"},
    "5fda81017f5b4e77aede2b8641bfa86b":{
      "scriptId":"u5"},
    "e42f8bb3386b4764be0c0c034b52de93":{
      "scriptId":"u6"},
    "b139b0d2a0db4d1ba8fc36f4932ea123":{
      "scriptId":"u7"},
    "fdd5ccaeabe246fa8889dd7d9c4ac8c8":{
      "scriptId":"u8"},
    "9be7c17d9efb45d19bafcbf130e3544b":{
      "scriptId":"u9"},
    "4b7ca7dd7d134bfa806c95d5eac1ccc1":{
      "scriptId":"u10"},
    "97e9111bf32d41c49911d61c80015080":{
      "scriptId":"u11"},
    "fa6abea2bca34f9e808a657e2f08a1c2":{
      "scriptId":"u12"},
    "a930fdd4abd74848aa8c8a2a1c8a7d2d":{
      "scriptId":"u13"},
    "58621cd637954c1382c76b09b8f4a524":{
      "scriptId":"u14"},
    "4ff4cb67dca54716a376556e5ea20960":{
      "scriptId":"u15"},
    "798967be86c04f91a254761557712211":{
      "scriptId":"u16"},
    "4c23b325341c4ae485f478d92e2fdf33":{
      "scriptId":"u17"},
    "321306a91ed148ca95e952220bd25999":{
      "scriptId":"u18"},
    "56c0f46a4b5e4f949c11f9a8c69bb171":{
      "scriptId":"u19"},
    "712074d7da2a405189df9701e7fbfbf5":{
      "scriptId":"u20"},
    "5e0ce07fc0e84cff90a6f6742c3fcbe4":{
      "scriptId":"u21"},
    "fd6fa6a9cb684aae813ecee3b390e290":{
      "scriptId":"u22"},
    "f959ba222daa4e49aab64e67cc101e92":{
      "scriptId":"u23"},
    "2c6555faffda4e66ae24d494151150b4":{
      "scriptId":"u24"},
    "e2d95a4a11364b278cff6e2ad82042b1":{
      "scriptId":"u25"},
    "7d084b3fc21e40c0be4e0934881e3a0a":{
      "scriptId":"u26"},
    "b6fffe6b87804661838b5bd86dea465d":{
      "scriptId":"u27"},
    "a408485f149e41de8a39182d487a0436":{
      "scriptId":"u28"},
    "14c367401ae04f73840d973857b67c95":{
      "scriptId":"u29"},
    "58f3bdbcfd8544438ee73f49dd4e4f3c":{
      "scriptId":"u30"},
    "3c56dc089e9a41f58e4ac5f7cddf243c":{
      "scriptId":"u31"},
    "5827232483074b8995c3b2925f25f92d":{
      "scriptId":"u32"},
    "102c2e6ebbd44130a68775b7c765968d":{
      "scriptId":"u33"},
    "4a234f1680af418c8f662770fc927290":{
      "scriptId":"u34"},
    "6013fefe84ea4f75bdcaadc437bc0789":{
      "scriptId":"u35"},
    "d30cc8e0cdef4edeb001a83d4fb47829":{
      "scriptId":"u36"},
    "514bed839fff4383b77c9b9a6d5c7882":{
      "scriptId":"u37"},
    "31350cfcdb0b44f982b4e0c39360a44a":{
      "scriptId":"u38"},
    "48ee8c3754f64da8836891b680c85235":{
      "scriptId":"u39"},
    "52b5a0c4d3e14c72a8017c4d56b0020b":{
      "scriptId":"u40"},
    "41e1d2a0712341058b4b5a433239d27c":{
      "scriptId":"u41"},
    "f089b396ad6642ba892d0853c9c081dd":{
      "scriptId":"u42"},
    "14f2bbb30f25483eb52ed6f8d38e8ced":{
      "scriptId":"u43"},
    "1002516d969f44c996fe69fc90013568":{
      "scriptId":"u44"},
    "380e9a3d72ae47799ca561bcc56c9d03":{
      "scriptId":"u45"},
    "52ed4607524a43f1babd984c2431695f":{
      "scriptId":"u46"},
    "a08437fc4cad4eaab7ce668a1faab5bf":{
      "scriptId":"u47"}}});