$axure.loadCurrentPage({
  "url":"1.html",
  "generationDate":new Date(1467728910824.63),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2b10d1fbb87e451f932e0d24f72a6699",
    "type":"Axure:Page",
    "name":"1",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d7cc84042c0b4162929fb61c1c1c7576",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":414,
              "height":716}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e9a5839290c41d4ab908ab1284e7a6f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":414,
                  "height":716}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1/u0.png"}},
{
          "id":"172b18aa526d44c1abc167ae1d613ebe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":117.5,
              "y":50},
            "size":{
              "width":154,
              "height":154},
            "borderWidth":"4",
            "cornerRadiusTopLeft":"80"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5726f013b6634189b36c10b02ec78f2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":117.5,
                  "y":50},
                "size":{
                  "width":154,
                  "height":154},
                "borderWidth":"4",
                "cornerRadiusTopLeft":"80"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/名帖1/u3.png"}},
{
          "id":"ccf2feccb3d2488f8d3045ccef69e9b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":127,
              "y":220},
            "size":{
              "width":145,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33e82739ec6e4be8912c70a9b7553ad3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":127,
                  "y":220},
                "size":{
                  "width":145,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7fa4c02659b94f7590116b4a16b50882",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":30,
              "y":280},
            "size":{
              "width":340,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18e61ccd055b4d46853174f8ea1d1a48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":30,
                  "y":280},
                "size":{
                  "width":340,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"976240d58910461e8d2f8fc75e243d9b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":155,
              "y":617},
            "size":{
              "width":79,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eabe5aae0d4f4bce8d2dd182399bc9ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":155,
                  "y":617},
                "size":{
                  "width":79,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 2 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"2.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/名帖1/u22.png"}},
{
          "id":"759963720b184a7ca165f0c22f8b8bed",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":45,
              "y":380},
            "size":{
              "width":10,
              "height":200},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/pc-页签个人介绍/u98_line.png"}},
{
          "id":"e3f20e2939f34a8dac451be37e1ac667",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":392},
            "size":{
              "width":12,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"686cffd154994fd7aa61b6521ccf81ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":44,
                  "y":392},
                "size":{
                  "width":12,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pc-页签个人介绍/u103.png"}},
{
          "id":"a96d647a6b9343678628357acffbc25f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":434},
            "size":{
              "width":12,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2f4ce595ec449cb97f5bccbb8d1d916",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":44,
                  "y":434},
                "size":{
                  "width":12,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pc-页签个人介绍/u103.png"}},
{
          "id":"6e8e8eea5eed4d1faf3ab8862cf71199",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":474},
            "size":{
              "width":12,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42509eea02c647afad7b75484755e915",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":44,
                  "y":474},
                "size":{
                  "width":12,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pc-页签个人介绍/u103.png"}},
{
          "id":"3ff548593615420394eab0075f60ff14",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":514},
            "size":{
              "width":12,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9c2cb1f6aea4cab854624d47ce1bedb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":44,
                  "y":514},
                "size":{
                  "width":12,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pc-页签个人介绍/u103.png"}},
{
          "id":"ce8b2e5547344309ab5e652bb78b0758",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":558},
            "size":{
              "width":12,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fa831efe09a42f1a023bb138d339043",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":44,
                  "y":558},
                "size":{
                  "width":12,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pc-页签个人介绍/u103.png"}},
{
          "id":"31d63f3d932444c78da29bf87c5ad478",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":64,
              "y":390},
            "size":{
              "width":102,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2e64bbc5cbe4ba39c8047f89b8d0256",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":64,
                  "y":390},
                "size":{
                  "width":102,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"600aa9622e904e409057150947234537",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":64,
              "y":430},
            "size":{
              "width":209,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8582a35e6ef04e6ca690d23e14ecb72b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":64,
                  "y":430},
                "size":{
                  "width":209,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"220801f47f92439b80024ed010a812f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":64,
              "y":472},
            "size":{
              "width":260,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47d1008d3d5d482f93bfb44985ef68bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":64,
                  "y":472},
                "size":{
                  "width":260,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"faf6165a79b143459d0fc2603b4fa232",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":64,
              "y":512},
            "size":{
              "width":284,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5edf9bb969241d88c706c806057ae49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":64,
                  "y":512},
                "size":{
                  "width":284,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3ee14f553f4a413db8914e2c244f92cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":62,
              "y":554},
            "size":{
              "width":206,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7780c07461924b0782faabcfa1d1a27f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":62,
                  "y":554},
                "size":{
                  "width":206,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1da12c2d2f4348deb3aa14fdbad32d62",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":158},
            "size":{
              "width":48,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3139ee1dc2a74545812b5d7d5577075f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":158},
                "size":{
                  "width":48,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/名帖1/u45.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "d7cc84042c0b4162929fb61c1c1c7576":{
      "scriptId":"u0"},
    "3e9a5839290c41d4ab908ab1284e7a6f":{
      "scriptId":"u1"},
    "172b18aa526d44c1abc167ae1d613ebe":{
      "scriptId":"u2"},
    "5726f013b6634189b36c10b02ec78f2d":{
      "scriptId":"u3"},
    "ccf2feccb3d2488f8d3045ccef69e9b3":{
      "scriptId":"u4"},
    "33e82739ec6e4be8912c70a9b7553ad3":{
      "scriptId":"u5"},
    "7fa4c02659b94f7590116b4a16b50882":{
      "scriptId":"u6"},
    "18e61ccd055b4d46853174f8ea1d1a48":{
      "scriptId":"u7"},
    "976240d58910461e8d2f8fc75e243d9b":{
      "scriptId":"u8"},
    "eabe5aae0d4f4bce8d2dd182399bc9ea":{
      "scriptId":"u9"},
    "759963720b184a7ca165f0c22f8b8bed":{
      "scriptId":"u10"},
    "e3f20e2939f34a8dac451be37e1ac667":{
      "scriptId":"u11"},
    "686cffd154994fd7aa61b6521ccf81ce":{
      "scriptId":"u12"},
    "a96d647a6b9343678628357acffbc25f":{
      "scriptId":"u13"},
    "b2f4ce595ec449cb97f5bccbb8d1d916":{
      "scriptId":"u14"},
    "6e8e8eea5eed4d1faf3ab8862cf71199":{
      "scriptId":"u15"},
    "42509eea02c647afad7b75484755e915":{
      "scriptId":"u16"},
    "3ff548593615420394eab0075f60ff14":{
      "scriptId":"u17"},
    "d9c2cb1f6aea4cab854624d47ce1bedb":{
      "scriptId":"u18"},
    "ce8b2e5547344309ab5e652bb78b0758":{
      "scriptId":"u19"},
    "4fa831efe09a42f1a023bb138d339043":{
      "scriptId":"u20"},
    "31d63f3d932444c78da29bf87c5ad478":{
      "scriptId":"u21"},
    "d2e64bbc5cbe4ba39c8047f89b8d0256":{
      "scriptId":"u22"},
    "600aa9622e904e409057150947234537":{
      "scriptId":"u23"},
    "8582a35e6ef04e6ca690d23e14ecb72b":{
      "scriptId":"u24"},
    "220801f47f92439b80024ed010a812f7":{
      "scriptId":"u25"},
    "47d1008d3d5d482f93bfb44985ef68bc":{
      "scriptId":"u26"},
    "faf6165a79b143459d0fc2603b4fa232":{
      "scriptId":"u27"},
    "e5edf9bb969241d88c706c806057ae49":{
      "scriptId":"u28"},
    "3ee14f553f4a413db8914e2c244f92cd":{
      "scriptId":"u29"},
    "7780c07461924b0782faabcfa1d1a27f":{
      "scriptId":"u30"},
    "1da12c2d2f4348deb3aa14fdbad32d62":{
      "scriptId":"u31"},
    "3139ee1dc2a74545812b5d7d5577075f":{
      "scriptId":"u32"}}});