$axure.loadCurrentPage({
  "url":"大牌词条新增.html",
  "generationDate":new Date(1467728161415.71),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0e2ffd6659f54394ba3d1d6ae4adda7f",
    "type":"Axure:Page",
    "name":"大牌词条新增",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6f35a16aebc247a590ef121c21447a35",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-1,
              "y":-1},
            "size":{
              "width":1362,
              "height":502}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"121e260943d7425283c4aa4e1e0f7b9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-1,
                  "y":-1},
                "size":{
                  "width":1362,
                  "height":502}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/百科后台-百科大牌/u0.png"}},
{
          "id":"5028b5dce65f4c42bdaa82e8feb2f8c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1963AA,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":37,
              "y":174},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b649619f69fb4664ba04e6d9f94284fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1963AA,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":37,
                  "y":174},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/百科后台-百科大牌/u2.png"}},
{
          "id":"e0bb9340a383402e8fd1757566ef2a81",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":37,
              "y":210},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e81dc36bcee4a1aa2c4ce7b6ecab4c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":37,
                  "y":210},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/百科后台-百科大牌/u2.png"}},
{
          "id":"9327841fcc7042ae97a0886f009f38c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":90},
            "size":{
              "width":360,
              "height":100},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dbe65f680c8549cc8d3d49f777d7c75e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":90},
                "size":{
                  "width":360,
                  "height":100},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/百科后台-百科大牌/u6.png"}},
{
          "id":"a00b22bc66ad4afa9920b7b00350c677",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":37,
              "y":246},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"174c0d3a716740e79464de4a83aee1ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":37,
                  "y":246},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/百科后台-百科大牌/u8.png"}},
{
          "id":"0265af81791a4371ba72ca4fa947d0fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":36,
              "y":282},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76dfa2847dbb460ca6dfb57db5506b72",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":36,
                  "y":282},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/百科后台-百科大牌/u10.png"}},
{
          "id":"2a96ce48988d40409d976a642999b1c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF5F5F5},
            "location":{
              "x":219,
              "y":57},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91d51cea156b458190d951028a2a202e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F5F5},
                "location":{
                  "x":219,
                  "y":57},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/百科后台-百科大牌/u12.png"}},
{
          "id":"cb60fddb497d4ac4af720d7d1d0861bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF5F5F5},
            "location":{
              "x":283,
              "y":57},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c369577f099349b4b2abb21d816574bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F5F5},
                "location":{
                  "x":283,
                  "y":57},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/百科后台-百科大牌/u12.png"}},
{
          "id":"bde5e2f7df2146f1be1952055b8abe9f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000CC,
              "opacity":1},
            "location":{
              "x":150,
              "y":100},
            "size":{
              "width":290,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"396811ac43fa4559bafeed4edae7f727",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000CC,
                  "opacity":1},
                "location":{
                  "x":150,
                  "y":100},
                "size":{
                  "width":290,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fc5848af6b144dd0949751079ee61348",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":132},
            "size":{
              "width":1211,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/百科后台-百科大牌/u18_line.png"}},
{
          "id":"81bbb2634d1d42cca97199c13b81a4a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":146,
              "y":154},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89a71e4b492f4e7fa66cf48712079851",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":146,
                  "y":154},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"805e03ee0f11415086e29ce760ddc4f0",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":211,
              "y":153},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onSelectionChange":{
              "description":"OnSelectionChange",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Show (Dynamic Panel)",
                      "objectsToFades":[{
                          "objectPath":["ed3c7f5cb06d41c7bbd626602f69c75d"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}}},
{
          "id":"ed3c7f5cb06d41c7bbd626602f69c75d",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":148,
              "y":183},
            "size":{
              "width":700,
              "height":507},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"2af180eaf4a94bb2b4639733e14e83c7",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"3bb37cb6e5d440bb901c5971fcf90f1e",
                  "label":"",
                  "parentDynamicPanel":"ed3c7f5cb06d41c7bbd626602f69c75d",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":13,
                      "y":17},
                    "size":{
                      "width":57,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"acd0059efbfc43bfa91cb0be482f8226",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ed3c7f5cb06d41c7bbd626602f69c75d",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":13,
                          "y":17},
                        "size":{
                          "width":57,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d0f18f89dfcb441ba8b85d38ed913cd1",
                  "label":"",
                  "parentDynamicPanel":"ed3c7f5cb06d41c7bbd626602f69c75d",
                  "panelIndex":0,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":76,
                      "y":13},
                    "size":{
                      "width":200,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"a4ea0d7c55154950a05ad5a4128343c5",
                  "label":"",
                  "parentDynamicPanel":"ed3c7f5cb06d41c7bbd626602f69c75d",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":296,
                      "y":17},
                    "size":{
                      "width":57,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b5fc506b83e44954995be29d9b960c9f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ed3c7f5cb06d41c7bbd626602f69c75d",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":296,
                          "y":17},
                        "size":{
                          "width":57,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7bfbfea5c1114440914846a7f3994c95",
                  "label":"",
                  "parentDynamicPanel":"ed3c7f5cb06d41c7bbd626602f69c75d",
                  "panelIndex":0,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":363,
                      "y":13},
                    "size":{
                      "width":200,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"be0d610405544ebd8b9de58ac2f46afc",
                  "label":"",
                  "parentDynamicPanel":"ed3c7f5cb06d41c7bbd626602f69c75d",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":11,
                      "y":60},
                    "size":{
                      "width":66,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0cfad0e76537434bad3e73df5c4ccb1b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ed3c7f5cb06d41c7bbd626602f69c75d",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":11,
                          "y":60},
                        "size":{
                          "width":66,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7f7584255cb94765a7e439156f6a5c2b",
                  "label":"",
                  "parentDynamicPanel":"ed3c7f5cb06d41c7bbd626602f69c75d",
                  "panelIndex":0,
                  "type":"textArea",
                  "styleType":"textArea",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":80,
                      "y":62},
                    "size":{
                      "width":481,
                      "height":100}},
                  "adaptiveStyles":{
}},
{
                  "id":"8ae3467e05fe4a819fac90c25b95fdae",
                  "label":"",
                  "parentDynamicPanel":"ed3c7f5cb06d41c7bbd626602f69c75d",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":173},
                    "size":{
                      "width":66,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c60c5f2253e945fd8c5cbc73ff302798",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ed3c7f5cb06d41c7bbd626602f69c75d",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":173},
                        "size":{
                          "width":66,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"4d912b35bbe8407c8a7f9fb04ac6742e",
                  "label":"",
                  "parentDynamicPanel":"ed3c7f5cb06d41c7bbd626602f69c75d",
                  "panelIndex":0,
                  "type":"checkbox",
                  "styleType":"checkbox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":86,
                      "y":173},
                    "size":{
                      "width":100,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"13606100a49942bfa07e768787b552d7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ed3c7f5cb06d41c7bbd626602f69c75d",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":86,
                          "y":173},
                        "size":{
                          "width":100,
                          "height":16}},
                      "adaptiveStyles":{
}}]},
{
                  "id":"1988623798bd436a99a7ce1d4e2d3daf",
                  "label":"",
                  "parentDynamicPanel":"ed3c7f5cb06d41c7bbd626602f69c75d",
                  "panelIndex":0,
                  "type":"checkbox",
                  "styleType":"checkbox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":167,
                      "y":174},
                    "size":{
                      "width":100,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1e555364298a447fad17b4b0cc8d58be",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ed3c7f5cb06d41c7bbd626602f69c75d",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":167,
                          "y":174},
                        "size":{
                          "width":100,
                          "height":16}},
                      "adaptiveStyles":{
}}]},
{
                  "id":"a26fcafe635e4316ad60ab32d613f1e1",
                  "label":"",
                  "parentDynamicPanel":"ed3c7f5cb06d41c7bbd626602f69c75d",
                  "panelIndex":0,
                  "type":"checkbox",
                  "styleType":"checkbox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":253,
                      "y":174},
                    "size":{
                      "width":100,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"81bcaa9b957c4624a20b0992c6694ae2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ed3c7f5cb06d41c7bbd626602f69c75d",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":253,
                          "y":174},
                        "size":{
                          "width":100,
                          "height":16}},
                      "adaptiveStyles":{
}}]},
{
                  "id":"9eaeb493b83040d3995ab9fd859205f5",
                  "label":"",
                  "parentDynamicPanel":"ed3c7f5cb06d41c7bbd626602f69c75d",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":212},
                    "size":{
                      "width":66,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c63050f70a84423c87dd165cb2251bc0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ed3c7f5cb06d41c7bbd626602f69c75d",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":212},
                        "size":{
                          "width":66,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7535b446a130454fad471c84a9bc92e8",
                  "label":"",
                  "parentDynamicPanel":"ed3c7f5cb06d41c7bbd626602f69c75d",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":245},
                    "size":{
                      "width":66,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ab81bbda800048d2bbbf2fdec0ef4aa5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ed3c7f5cb06d41c7bbd626602f69c75d",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":245},
                        "size":{
                          "width":66,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8fb9ecb0029c4f9da15592738ced524a",
                  "label":"",
                  "parentDynamicPanel":"ed3c7f5cb06d41c7bbd626602f69c75d",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":76,
                      "y":245},
                    "size":{
                      "width":79,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d1bc26d464ab4ef3a04c0d15f886cbbe",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ed3c7f5cb06d41c7bbd626602f69c75d",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":76,
                          "y":245},
                        "size":{
                          "width":79,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e1d8407b314848ceafa1dd4eece83c8f",
                  "label":"",
                  "parentDynamicPanel":"ed3c7f5cb06d41c7bbd626602f69c75d",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":77,
                      "y":276},
                    "size":{
                      "width":28,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9fd9f5c69467468dbb73570e0d7aa6ca",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ed3c7f5cb06d41c7bbd626602f69c75d",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":77,
                          "y":276},
                        "size":{
                          "width":28,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"89ea3844743c4fc4a7e5c6d82996c7e9",
                  "label":"",
                  "parentDynamicPanel":"ed3c7f5cb06d41c7bbd626602f69c75d",
                  "panelIndex":0,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":105,
                      "y":276},
                    "size":{
                      "width":200,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"fcaec9a913594cdaa7c9442a4fd7fe19",
                  "label":"",
                  "parentDynamicPanel":"ed3c7f5cb06d41c7bbd626602f69c75d",
                  "panelIndex":0,
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":155,
                      "y":238},
                    "size":{
                      "width":100,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"3898678868a2454da396cad4940795b8",
                  "label":"",
                  "parentDynamicPanel":"ed3c7f5cb06d41c7bbd626602f69c75d",
                  "panelIndex":0,
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":253,
                      "y":305},
                    "size":{
                      "width":100,
                      "height":25}},
                  "adaptiveStyles":{
}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "6f35a16aebc247a590ef121c21447a35":{
      "scriptId":"u0"},
    "121e260943d7425283c4aa4e1e0f7b9b":{
      "scriptId":"u1"},
    "5028b5dce65f4c42bdaa82e8feb2f8c4":{
      "scriptId":"u2"},
    "b649619f69fb4664ba04e6d9f94284fe":{
      "scriptId":"u3"},
    "e0bb9340a383402e8fd1757566ef2a81":{
      "scriptId":"u4"},
    "2e81dc36bcee4a1aa2c4ce7b6ecab4c3":{
      "scriptId":"u5"},
    "9327841fcc7042ae97a0886f009f38c1":{
      "scriptId":"u6"},
    "dbe65f680c8549cc8d3d49f777d7c75e":{
      "scriptId":"u7"},
    "a00b22bc66ad4afa9920b7b00350c677":{
      "scriptId":"u8"},
    "174c0d3a716740e79464de4a83aee1ce":{
      "scriptId":"u9"},
    "0265af81791a4371ba72ca4fa947d0fa":{
      "scriptId":"u10"},
    "76dfa2847dbb460ca6dfb57db5506b72":{
      "scriptId":"u11"},
    "2a96ce48988d40409d976a642999b1c3":{
      "scriptId":"u12"},
    "91d51cea156b458190d951028a2a202e":{
      "scriptId":"u13"},
    "cb60fddb497d4ac4af720d7d1d0861bb":{
      "scriptId":"u14"},
    "c369577f099349b4b2abb21d816574bd":{
      "scriptId":"u15"},
    "bde5e2f7df2146f1be1952055b8abe9f":{
      "scriptId":"u16"},
    "396811ac43fa4559bafeed4edae7f727":{
      "scriptId":"u17"},
    "fc5848af6b144dd0949751079ee61348":{
      "scriptId":"u18"},
    "81bbb2634d1d42cca97199c13b81a4a2":{
      "scriptId":"u19"},
    "89a71e4b492f4e7fa66cf48712079851":{
      "scriptId":"u20"},
    "805e03ee0f11415086e29ce760ddc4f0":{
      "scriptId":"u21"},
    "ed3c7f5cb06d41c7bbd626602f69c75d":{
      "scriptId":"u22"},
    "3bb37cb6e5d440bb901c5971fcf90f1e":{
      "scriptId":"u23"},
    "acd0059efbfc43bfa91cb0be482f8226":{
      "scriptId":"u24"},
    "d0f18f89dfcb441ba8b85d38ed913cd1":{
      "scriptId":"u25"},
    "a4ea0d7c55154950a05ad5a4128343c5":{
      "scriptId":"u26"},
    "b5fc506b83e44954995be29d9b960c9f":{
      "scriptId":"u27"},
    "7bfbfea5c1114440914846a7f3994c95":{
      "scriptId":"u28"},
    "be0d610405544ebd8b9de58ac2f46afc":{
      "scriptId":"u29"},
    "0cfad0e76537434bad3e73df5c4ccb1b":{
      "scriptId":"u30"},
    "7f7584255cb94765a7e439156f6a5c2b":{
      "scriptId":"u31"},
    "8ae3467e05fe4a819fac90c25b95fdae":{
      "scriptId":"u32"},
    "c60c5f2253e945fd8c5cbc73ff302798":{
      "scriptId":"u33"},
    "4d912b35bbe8407c8a7f9fb04ac6742e":{
      "scriptId":"u34"},
    "13606100a49942bfa07e768787b552d7":{
      "scriptId":"u35"},
    "1988623798bd436a99a7ce1d4e2d3daf":{
      "scriptId":"u36"},
    "1e555364298a447fad17b4b0cc8d58be":{
      "scriptId":"u37"},
    "a26fcafe635e4316ad60ab32d613f1e1":{
      "scriptId":"u38"},
    "81bcaa9b957c4624a20b0992c6694ae2":{
      "scriptId":"u39"},
    "9eaeb493b83040d3995ab9fd859205f5":{
      "scriptId":"u40"},
    "c63050f70a84423c87dd165cb2251bc0":{
      "scriptId":"u41"},
    "7535b446a130454fad471c84a9bc92e8":{
      "scriptId":"u42"},
    "ab81bbda800048d2bbbf2fdec0ef4aa5":{
      "scriptId":"u43"},
    "8fb9ecb0029c4f9da15592738ced524a":{
      "scriptId":"u44"},
    "d1bc26d464ab4ef3a04c0d15f886cbbe":{
      "scriptId":"u45"},
    "e1d8407b314848ceafa1dd4eece83c8f":{
      "scriptId":"u46"},
    "9fd9f5c69467468dbb73570e0d7aa6ca":{
      "scriptId":"u47"},
    "89ea3844743c4fc4a7e5c6d82996c7e9":{
      "scriptId":"u48"},
    "fcaec9a913594cdaa7c9442a4fd7fe19":{
      "scriptId":"u49"},
    "3898678868a2454da396cad4940795b8":{
      "scriptId":"u50"}}});