$axure.loadCurrentPage({
  "url":"名帖3.html",
  "generationDate":new Date(1467728910730.52),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9801ec4d4d7a42c79273638cec801f11",
    "type":"Axure:Page",
    "name":"名帖3",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5d8d750839f441ac83b38d96441ee0cd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":116,
              "y":12},
            "size":{
              "width":424,
              "height":848},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ee8cbb9820e4553a0ca0b5b084b1f74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":116,
                  "y":12},
                "size":{
                  "width":424,
                  "height":848},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/名帖1/u0.png"}},
{
          "id":"904900efc52444919afd6026ee26c614",
          "label":"",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":141,
              "y":101},
            "size":{
              "width":375,
              "height":667}},
          "adaptiveStyles":{
},
          "target":{
            "targetType":"webUrl",
            "urlLiteral":{
              "exprType":"stringLiteral",
              "value":"",
              "stos":[]},
            "includeVariables":false}},
{
          "id":"8c33c27635a846adbde2f54d2b2c3a86",
          "label":"time_panel",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":141,
              "y":101},
            "size":{
              "width":375,
              "height":20},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e64da07626b942c3bdff534702765df4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":141,
                  "y":101},
                "size":{
                  "width":375,
                  "height":20},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/名帖1/time_panel_u9.png"}},
{
          "id":"e549032087cf4a1a988a285152aa7080",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'IOS8-Icons Regular', 'IOS8-Icons'",
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":179,
              "y":101},
            "size":{
              "width":22,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ddbe6b8f84d3492294649a4dbf8c1353",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'IOS8-Icons Regular', 'IOS8-Icons'",
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":179,
                  "y":101},
                "size":{
                  "width":22,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/名帖1/u11.png"}},
{
          "id":"750af167282b4afd84865a3244132a2d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":146,
              "y":109},
            "size":{
              "width":33,
              "height":5}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fcd6f96f5e0a4faf93c1ac8680007110",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":146,
                  "y":109},
                "size":{
                  "width":33,
                  "height":5}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/名帖1/u13.png"}},
{
          "id":"22b5ba12cf7d4ee48e2a464750221305",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":481,
              "y":106},
            "size":{
              "width":25,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b58af1b5ad6942c4a34a1b5bf5f12400",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":481,
                  "y":106},
                "size":{
                  "width":25,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/名帖1/u15.png"}},
{
          "id":"1b77283f253047089e8df6852ee02501",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":450,
              "y":103},
            "size":{
              "width":31,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8de4f84fbb6d466da9b2583fa18a5bc9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":450,
                  "y":103},
                "size":{
                  "width":31,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/名帖1/u17.png"}},
{
          "id":"e72aaa859570472a8fab7bbece16f51d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'IOS8-Icons Regular', 'IOS8-Icons'",
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":428,
              "y":101},
            "size":{
              "width":22,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62d572eff4ad48c38fd4d5c1cd679075",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'IOS8-Icons Regular', 'IOS8-Icons'",
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":428,
                  "y":101},
                "size":{
                  "width":22,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/名帖1/u11.png"}},
{
          "id":"604cdf9dd7ff4d26a3f599e13075cb99",
          "label":"timer",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":291,
              "y":101},
            "size":{
              "width":18,
              "height":20}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onPanelStateChange":{
              "description":"OnPanelStateChange",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set text on time_panel equal to &quot;[['0'.concat(hours).slice(-...&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["e64da07626b942c3bdff534702765df4"]},
{
                                "exprType":"stringLiteral",
                                "value":"[['0'.concat(hours).slice(-2)]]:[['0'.concat(minutes).slice(-2)]]",
                                "localVariables":{
},
                                "stos":[{
                                    "computedType":"string",
                                    "sto":"fCall",
                                    "thisSTO":{
                                      "computedType":"string",
                                      "desiredType":"string",
                                      "sto":"fCall",
                                      "thisSTO":{
                                        "computedType":"string",
                                        "desiredType":"string",
                                        "sto":"literal",
                                        "value":"0"},
                                      "func":"concat",
                                      "arguments":[{
                                          "sto":"var",
                                          "name":"hours"}]},
                                    "func":"slice",
                                    "arguments":[{
                                        "computedType":"int",
                                        "sto":"unOp",
                                        "op":"-",
                                        "inputSTO":{
                                          "computedType":"int",
                                          "sto":"literal",
                                          "value":2}}]},
{
                                    "computedType":"string",
                                    "sto":"fCall",
                                    "thisSTO":{
                                      "computedType":"string",
                                      "desiredType":"string",
                                      "sto":"fCall",
                                      "thisSTO":{
                                        "computedType":"string",
                                        "desiredType":"string",
                                        "sto":"literal",
                                        "value":"0"},
                                      "func":"concat",
                                      "arguments":[{
                                          "sto":"var",
                                          "name":"minutes"}]},
                                    "func":"slice",
                                    "arguments":[{
                                        "computedType":"int",
                                        "sto":"unOp",
                                        "op":"-",
                                        "inputSTO":{
                                          "computedType":"int",
                                          "sto":"literal",
                                          "value":2}}]}]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]}]}}]}]},
            "onLoad":{
              "description":"OnLoad",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set timer to Next wrap repeat every 60000 ms",
                      "panelsToStates":[{
                          "panelPath":["604cdf9dd7ff4d26a3f599e13075cb99"],
                          "stateInfo":{
                            "setStateType":"next",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":true,
                            "showWhenSet":false,
                            "repeat":60000,
                            "options":{
                              "compress":false}}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"cd0ee95d93164b43b0896c4c6fdaf23e",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"fc1b3e7f66f64b51b1234c53b625f54e",
              "label":"State2",
              "type":"Axure:PanelDiagram",
              "objects":[],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"1337b2ac791d4551a0df90e2c049aa66",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":167,
              "y":153},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"372d7e6a2b2846efa98e71090f54daa4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":167,
                  "y":153},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4620c910a9d7456794d54ed23015f68c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":271,
              "y":217},
            "size":{
              "width":235,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c1bdad8ba2149dd888287d643f8a7ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":271,
                  "y":217},
                "size":{
                  "width":235,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cd9adcf93ee2415391339736c2cbfcd6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":270,
              "y":248},
            "size":{
              "width":236,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64a5f5d3f45048bb8cfd9c576029af30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":270,
                  "y":248},
                "size":{
                  "width":236,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8c6e6881bd894ea0bb6486826fc972ea",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":161,
              "y":318},
            "size":{
              "width":332,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/名帖3/u22_line.png"}},
{
          "id":"95d6b589430b447fad1d22ced528bd37",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":162,
              "y":208},
            "size":{
              "width":98,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8df5c40d6a5a435f8422055d46e17c27",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":162,
                  "y":208},
                "size":{
                  "width":98,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/名帖3/u23.png"}},
{
          "id":"f3bb89a90f6848f5af4fde692a1fb06a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":273,
              "y":355},
            "size":{
              "width":235,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"732b85cc55234cd288ad7d1e234b35d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":273,
                  "y":355},
                "size":{
                  "width":235,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"98887df2f2e748f8b1b655244b073f26",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":272,
              "y":386},
            "size":{
              "width":236,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a565ab68d97f4930b90655d4977c856a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":272,
                  "y":386},
                "size":{
                  "width":236,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f703f790a57846d9b8eedac13ee61eb8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":163,
              "y":456},
            "size":{
              "width":332,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/名帖3/u22_line.png"}},
{
          "id":"cc15972ae755469ab3661d0c8688409e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":164,
              "y":346},
            "size":{
              "width":98,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12ee318d981f4f1ea294c959d3097171",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":164,
                  "y":346},
                "size":{
                  "width":98,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/名帖3/u23.png"}},
{
          "id":"c7cf640dbc01473db29a4f1269912048",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":274,
              "y":494},
            "size":{
              "width":235,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"166f8892ff3c45cf9eb59c87fa5a75de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":274,
                  "y":494},
                "size":{
                  "width":235,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d0dc440328e04323938a596b52b9b89d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":273,
              "y":525},
            "size":{
              "width":236,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48584eaf096840ec8de1a99845b69ee9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":273,
                  "y":525},
                "size":{
                  "width":236,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"56e2b8352f6a46648df38203be4b4f53",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":164,
              "y":595},
            "size":{
              "width":332,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/名帖3/u22_line.png"}},
{
          "id":"f1a63987ffbf4c9ba6d09f84cd79c72a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":165,
              "y":485},
            "size":{
              "width":98,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10527680bd3640caa774c6f77499f8b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":165,
                  "y":485},
                "size":{
                  "width":98,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/名帖3/u23.png"}},
{
          "id":"e28c62bbfb084981bd6d7e2fb3ccd550",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":275,
              "y":629},
            "size":{
              "width":235,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab289dd2737145e5bc9f2a39faa3ec4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":275,
                  "y":629},
                "size":{
                  "width":235,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a10b9dd329c44433bc5a0683d8fcac73",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":274,
              "y":660},
            "size":{
              "width":236,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2db420c41ba24806ad60ef1ac04a3ecf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":274,
                  "y":660},
                "size":{
                  "width":236,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f112078ab9ee4ddeb92b0ae38345ec2d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":166,
              "y":620},
            "size":{
              "width":98,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e31eb93ce421439689dbf810a094596c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":166,
                  "y":620},
                "size":{
                  "width":98,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/名帖3/u23.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "5d8d750839f441ac83b38d96441ee0cd":{
      "scriptId":"u0"},
    "0ee8cbb9820e4553a0ca0b5b084b1f74":{
      "scriptId":"u1"},
    "904900efc52444919afd6026ee26c614":{
      "scriptId":"u2"},
    "8c33c27635a846adbde2f54d2b2c3a86":{
      "scriptId":"u3"},
    "e64da07626b942c3bdff534702765df4":{
      "scriptId":"u4"},
    "e549032087cf4a1a988a285152aa7080":{
      "scriptId":"u5"},
    "ddbe6b8f84d3492294649a4dbf8c1353":{
      "scriptId":"u6"},
    "750af167282b4afd84865a3244132a2d":{
      "scriptId":"u7"},
    "fcd6f96f5e0a4faf93c1ac8680007110":{
      "scriptId":"u8"},
    "22b5ba12cf7d4ee48e2a464750221305":{
      "scriptId":"u9"},
    "b58af1b5ad6942c4a34a1b5bf5f12400":{
      "scriptId":"u10"},
    "1b77283f253047089e8df6852ee02501":{
      "scriptId":"u11"},
    "8de4f84fbb6d466da9b2583fa18a5bc9":{
      "scriptId":"u12"},
    "e72aaa859570472a8fab7bbece16f51d":{
      "scriptId":"u13"},
    "62d572eff4ad48c38fd4d5c1cd679075":{
      "scriptId":"u14"},
    "604cdf9dd7ff4d26a3f599e13075cb99":{
      "scriptId":"u15"},
    "1337b2ac791d4551a0df90e2c049aa66":{
      "scriptId":"u16"},
    "372d7e6a2b2846efa98e71090f54daa4":{
      "scriptId":"u17"},
    "4620c910a9d7456794d54ed23015f68c":{
      "scriptId":"u18"},
    "2c1bdad8ba2149dd888287d643f8a7ef":{
      "scriptId":"u19"},
    "cd9adcf93ee2415391339736c2cbfcd6":{
      "scriptId":"u20"},
    "64a5f5d3f45048bb8cfd9c576029af30":{
      "scriptId":"u21"},
    "8c6e6881bd894ea0bb6486826fc972ea":{
      "scriptId":"u22"},
    "95d6b589430b447fad1d22ced528bd37":{
      "scriptId":"u23"},
    "8df5c40d6a5a435f8422055d46e17c27":{
      "scriptId":"u24"},
    "f3bb89a90f6848f5af4fde692a1fb06a":{
      "scriptId":"u25"},
    "732b85cc55234cd288ad7d1e234b35d9":{
      "scriptId":"u26"},
    "98887df2f2e748f8b1b655244b073f26":{
      "scriptId":"u27"},
    "a565ab68d97f4930b90655d4977c856a":{
      "scriptId":"u28"},
    "f703f790a57846d9b8eedac13ee61eb8":{
      "scriptId":"u29"},
    "cc15972ae755469ab3661d0c8688409e":{
      "scriptId":"u30"},
    "12ee318d981f4f1ea294c959d3097171":{
      "scriptId":"u31"},
    "c7cf640dbc01473db29a4f1269912048":{
      "scriptId":"u32"},
    "166f8892ff3c45cf9eb59c87fa5a75de":{
      "scriptId":"u33"},
    "d0dc440328e04323938a596b52b9b89d":{
      "scriptId":"u34"},
    "48584eaf096840ec8de1a99845b69ee9":{
      "scriptId":"u35"},
    "56e2b8352f6a46648df38203be4b4f53":{
      "scriptId":"u36"},
    "f1a63987ffbf4c9ba6d09f84cd79c72a":{
      "scriptId":"u37"},
    "10527680bd3640caa774c6f77499f8b4":{
      "scriptId":"u38"},
    "e28c62bbfb084981bd6d7e2fb3ccd550":{
      "scriptId":"u39"},
    "ab289dd2737145e5bc9f2a39faa3ec4a":{
      "scriptId":"u40"},
    "a10b9dd329c44433bc5a0683d8fcac73":{
      "scriptId":"u41"},
    "2db420c41ba24806ad60ef1ac04a3ecf":{
      "scriptId":"u42"},
    "f112078ab9ee4ddeb92b0ae38345ec2d":{
      "scriptId":"u43"},
    "e31eb93ce421439689dbf810a094596c":{
      "scriptId":"u44"}}});