$axure.loadCurrentPage({
  "url":"2.html",
  "generationDate":new Date(1467728160556.93),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"66ef1e717cf9446eaa760077424fa385",
    "type":"Axure:Page",
    "name":"2",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9e2727e9a7c74b1aae55b76a904deaae",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":414,
              "height":716}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"996ea1ee47a044579837ab4314f134ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":414,
                  "height":716}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1/u0.png"}},
{
          "id":"d4d58625369b42d5b5b051eddb6cfec0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":163},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9a8ee81ae134787ba5558fdbe9a473e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":44,
                  "y":163},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/名帖2/u3.png"}},
{
          "id":"0fd9ec9c5f844713bf6513df14bc6648",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":92,
              "y":174},
            "size":{
              "width":145,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"616c15d9c53841b2bb8c31ab0f5df8db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":92,
                  "y":174},
                "size":{
                  "width":145,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"98cacb7fda5e429e8c1c81e5cf255118",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":174},
            "size":{
              "width":58,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd970afd5e204101adbfd2b8d19cca52",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":174},
                "size":{
                  "width":58,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/名帖2/u7.png"}},
{
          "id":"6ba527b459274c07824540afe1390392",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":47,
              "y":370},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"561f5012cb224078a39a9303ed6bf6b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":47,
                  "y":370},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/名帖2/u3.png"}},
{
          "id":"9ccdadaa0cb54f9e99caab9274716a1e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":95,
              "y":386},
            "size":{
              "width":145,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4713e25d40ff4b5ba3d6932be6efa55f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":95,
                  "y":386},
                "size":{
                  "width":145,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e8e1faec9f2b4a29b437159bf171ee07",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":273,
              "y":382},
            "size":{
              "width":58,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"050382a6511c46558a84b0956f2e811f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":273,
                  "y":382},
                "size":{
                  "width":58,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/名帖2/u7.png"}},
{
          "id":"cd9c612bc1e6465d90fe8c27bcdc362c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":47,
              "y":449},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4a44184349c43fc81a3e5d4d6284826",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":47,
                  "y":449},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/名帖2/u3.png"}},
{
          "id":"1d1d988c310d43f3b2291cff33c0ca96",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":95,
              "y":465},
            "size":{
              "width":145,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fcd618d2ef464a8e8298be2f27a87594",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":95,
                  "y":465},
                "size":{
                  "width":145,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e24ac8e1e5946e2919ea01b579e0291",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":47,
              "y":523},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e2d2cd040354f6ab34a4afecf1fead4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":47,
                  "y":523},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/名帖2/u3.png"}},
{
          "id":"7e014545283d4858a9ee17e7b5222ca7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":95,
              "y":539},
            "size":{
              "width":145,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6890b88f5a648fa90c0c9c7ea4ffb1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":95,
                  "y":539},
                "size":{
                  "width":145,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"11a27c378f3240bba321431035a00ca6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":273,
              "y":537},
            "size":{
              "width":58,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6f7e0445c6a410494f83f58d4e3e28b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":273,
                  "y":537},
                "size":{
                  "width":58,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/名帖2/u7.png"}},
{
          "id":"6a6a5bcb9fff40579b43d99c7673fe1f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":122,
              "y":219},
            "size":{
              "width":143,
              "height":135}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d24061fdd5134b659384e9b2260de5fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":122,
                  "y":219},
                "size":{
                  "width":143,
                  "height":135}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/名帖2/u38.png"}},
{
          "id":"fed1b655996846f49bf162dc03e50e2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":143,
              "y":354},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba42fbd212f74b64b834a33d6f16b52d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":143,
                  "y":354},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c552155e4e8488bbf9e0cdada3f57db",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":20,
              "y":28},
            "size":{
              "width":360,
              "height":112}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98d5ffac84374057839ab1bce09fa2bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":20,
                  "y":28},
                "size":{
                  "width":360,
                  "height":112}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"32c4046b24bf47f7860f8642b606810c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":468},
            "size":{
              "width":69,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d492e0604484e0a82797df941eefc3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":468},
                "size":{
                  "width":69,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"54939672416142e0ac115041580fa1b1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":149.5,
              "y":627},
            "size":{
              "width":79,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8cba5c6e15a74d9e9ccd977310c2eb5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":149.5,
                  "y":627},
                "size":{
                  "width":79,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/名帖1/u22.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "9e2727e9a7c74b1aae55b76a904deaae":{
      "scriptId":"u0"},
    "996ea1ee47a044579837ab4314f134ce":{
      "scriptId":"u1"},
    "d4d58625369b42d5b5b051eddb6cfec0":{
      "scriptId":"u2"},
    "d9a8ee81ae134787ba5558fdbe9a473e":{
      "scriptId":"u3"},
    "0fd9ec9c5f844713bf6513df14bc6648":{
      "scriptId":"u4"},
    "616c15d9c53841b2bb8c31ab0f5df8db":{
      "scriptId":"u5"},
    "98cacb7fda5e429e8c1c81e5cf255118":{
      "scriptId":"u6"},
    "fd970afd5e204101adbfd2b8d19cca52":{
      "scriptId":"u7"},
    "6ba527b459274c07824540afe1390392":{
      "scriptId":"u8"},
    "561f5012cb224078a39a9303ed6bf6b3":{
      "scriptId":"u9"},
    "9ccdadaa0cb54f9e99caab9274716a1e":{
      "scriptId":"u10"},
    "4713e25d40ff4b5ba3d6932be6efa55f":{
      "scriptId":"u11"},
    "e8e1faec9f2b4a29b437159bf171ee07":{
      "scriptId":"u12"},
    "050382a6511c46558a84b0956f2e811f":{
      "scriptId":"u13"},
    "cd9c612bc1e6465d90fe8c27bcdc362c":{
      "scriptId":"u14"},
    "d4a44184349c43fc81a3e5d4d6284826":{
      "scriptId":"u15"},
    "1d1d988c310d43f3b2291cff33c0ca96":{
      "scriptId":"u16"},
    "fcd618d2ef464a8e8298be2f27a87594":{
      "scriptId":"u17"},
    "7e24ac8e1e5946e2919ea01b579e0291":{
      "scriptId":"u18"},
    "4e2d2cd040354f6ab34a4afecf1fead4":{
      "scriptId":"u19"},
    "7e014545283d4858a9ee17e7b5222ca7":{
      "scriptId":"u20"},
    "d6890b88f5a648fa90c0c9c7ea4ffb1a":{
      "scriptId":"u21"},
    "11a27c378f3240bba321431035a00ca6":{
      "scriptId":"u22"},
    "b6f7e0445c6a410494f83f58d4e3e28b":{
      "scriptId":"u23"},
    "6a6a5bcb9fff40579b43d99c7673fe1f":{
      "scriptId":"u24"},
    "d24061fdd5134b659384e9b2260de5fc":{
      "scriptId":"u25"},
    "fed1b655996846f49bf162dc03e50e2b":{
      "scriptId":"u26"},
    "ba42fbd212f74b64b834a33d6f16b52d":{
      "scriptId":"u27"},
    "1c552155e4e8488bbf9e0cdada3f57db":{
      "scriptId":"u28"},
    "98d5ffac84374057839ab1bce09fa2bc":{
      "scriptId":"u29"},
    "32c4046b24bf47f7860f8642b606810c":{
      "scriptId":"u30"},
    "8d492e0604484e0a82797df941eefc3d":{
      "scriptId":"u31"},
    "54939672416142e0ac115041580fa1b1":{
      "scriptId":"u32"},
    "8cba5c6e15a74d9e9ccd977310c2eb5b":{
      "scriptId":"u33"}}});