$axure.loadCurrentPage({
  "url":"个性化模板.html",
  "generationDate":new Date(1467728162482.68),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"27bb4b315dcf485d830fad3a7ded81c1",
    "type":"Axure:Page",
    "name":"个性化模板",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"90f6010f64184d64b3c21bdfb26f992b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1360,
              "height":606}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"472b5e53f516467eb2f8e5327815a21b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1360,
                  "height":606}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个性化模板/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "90f6010f64184d64b3c21bdfb26f992b":{
      "scriptId":"u0"},
    "472b5e53f516467eb2f8e5327815a21b":{
      "scriptId":"u1"}}});