$axure.loadCurrentPage({
  "url":"3.html",
  "generationDate":new Date(1467728910987.75),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"00b2c63569334697b15037b381bacbd6",
    "type":"Axure:Page",
    "name":"3",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c0f9356b1d904f888624d413c5d4ad72",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":414,
              "height":716}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"338618862ad94f53a5284f985ba5a378",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":414,
                  "height":716}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1/u0.png"}},
{
          "id":"0e349c9bfc2c447a824da85d285d22f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":31,
              "y":30},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ddbb567e3e7048b8ab1a76f16dbc01c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":31,
                  "y":30},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3ea2f81849634c668d7629afd20551fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":135,
              "y":94},
            "size":{
              "width":235,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b496987ff56c4e2ba8993cd958878a7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":135,
                  "y":94},
                "size":{
                  "width":235,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d24fd85c262b4672a6e84646cf5ae831",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":134,
              "y":125},
            "size":{
              "width":236,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f51da77fcc054cafb8da628377c0667a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":134,
                  "y":125},
                "size":{
                  "width":236,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4255a7c38e0248be8f3fdf1c27082dc7",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":25,
              "y":195},
            "size":{
              "width":345,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/3/u8_line.png"}},
{
          "id":"6c019009f96647d895ab92d4cac294cf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":85},
            "size":{
              "width":98,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c48fa541a90c4e99b4cdf82bc21c00ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":85},
                "size":{
                  "width":98,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/名帖3/u23.png"}},
{
          "id":"c8348d12279a44348c4a34eeea885918",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":137,
              "y":232},
            "size":{
              "width":235,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c893c38974c4304b7d19e0b3e0fbcde",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":137,
                  "y":232},
                "size":{
                  "width":235,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"502679ef7189402ea35e40d01a7de3ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":136,
              "y":263},
            "size":{
              "width":236,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e2168609efe402bb14c9beffd98b1e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":136,
                  "y":263},
                "size":{
                  "width":236,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"54ff58db38da4d4d85d686e10d24e3ca",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":345},
            "size":{
              "width":343,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/3/u15_line.png"}},
{
          "id":"badaa594292d4a1e886de61ef7c452bb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":28,
              "y":223},
            "size":{
              "width":98,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbf48dd8a7264f8eb7c40e3f89c01430",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":28,
                  "y":223},
                "size":{
                  "width":98,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/名帖3/u23.png"}},
{
          "id":"9d7dff93afa341f89cbff2f8d3a76748",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":138,
              "y":378},
            "size":{
              "width":235,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9653ae0df3d24cc7ba56d8930eac8f5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":138,
                  "y":378},
                "size":{
                  "width":235,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ac8fe0dbc2b44023892505d2a63aabca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":137,
              "y":409},
            "size":{
              "width":236,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"592ec768f2464798a994ad94f8142468",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":137,
                  "y":409},
                "size":{
                  "width":236,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ee26944b7969422eab01938b69886819",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":28,
              "y":497},
            "size":{
              "width":342,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/3/u22_line.png"}},
{
          "id":"20c98f8f425649ff880777946eab8907",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":29,
              "y":369},
            "size":{
              "width":98,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf2e01e2c0bc461c93b05eb274282d0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":29,
                  "y":369},
                "size":{
                  "width":98,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/名帖3/u23.png"}},
{
          "id":"f9e5de79c7a44c939359d9a5ee5a8721",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":139,
              "y":542},
            "size":{
              "width":235,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2aa7e539beaa4cf58ed82f3f77b6f337",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":139,
                  "y":542},
                "size":{
                  "width":235,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a1d5067f5b5c44769ecaa9a5805d667a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":138,
              "y":573},
            "size":{
              "width":236,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d246d1c728e142e5b3251ff70b42eef3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":138,
                  "y":573},
                "size":{
                  "width":236,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"321ebd89974f49feaa1b5249a9a29e11",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":533},
            "size":{
              "width":98,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f04f253e87cc467bbebc7db1dccb9dda",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":533},
                "size":{
                  "width":98,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 1 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/名帖3/u23.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "c0f9356b1d904f888624d413c5d4ad72":{
      "scriptId":"u0"},
    "338618862ad94f53a5284f985ba5a378":{
      "scriptId":"u1"},
    "0e349c9bfc2c447a824da85d285d22f4":{
      "scriptId":"u2"},
    "ddbb567e3e7048b8ab1a76f16dbc01c5":{
      "scriptId":"u3"},
    "3ea2f81849634c668d7629afd20551fe":{
      "scriptId":"u4"},
    "b496987ff56c4e2ba8993cd958878a7a":{
      "scriptId":"u5"},
    "d24fd85c262b4672a6e84646cf5ae831":{
      "scriptId":"u6"},
    "f51da77fcc054cafb8da628377c0667a":{
      "scriptId":"u7"},
    "4255a7c38e0248be8f3fdf1c27082dc7":{
      "scriptId":"u8"},
    "6c019009f96647d895ab92d4cac294cf":{
      "scriptId":"u9"},
    "c48fa541a90c4e99b4cdf82bc21c00ae":{
      "scriptId":"u10"},
    "c8348d12279a44348c4a34eeea885918":{
      "scriptId":"u11"},
    "1c893c38974c4304b7d19e0b3e0fbcde":{
      "scriptId":"u12"},
    "502679ef7189402ea35e40d01a7de3ce":{
      "scriptId":"u13"},
    "1e2168609efe402bb14c9beffd98b1e5":{
      "scriptId":"u14"},
    "54ff58db38da4d4d85d686e10d24e3ca":{
      "scriptId":"u15"},
    "badaa594292d4a1e886de61ef7c452bb":{
      "scriptId":"u16"},
    "fbf48dd8a7264f8eb7c40e3f89c01430":{
      "scriptId":"u17"},
    "9d7dff93afa341f89cbff2f8d3a76748":{
      "scriptId":"u18"},
    "9653ae0df3d24cc7ba56d8930eac8f5c":{
      "scriptId":"u19"},
    "ac8fe0dbc2b44023892505d2a63aabca":{
      "scriptId":"u20"},
    "592ec768f2464798a994ad94f8142468":{
      "scriptId":"u21"},
    "ee26944b7969422eab01938b69886819":{
      "scriptId":"u22"},
    "20c98f8f425649ff880777946eab8907":{
      "scriptId":"u23"},
    "cf2e01e2c0bc461c93b05eb274282d0b":{
      "scriptId":"u24"},
    "f9e5de79c7a44c939359d9a5ee5a8721":{
      "scriptId":"u25"},
    "2aa7e539beaa4cf58ed82f3f77b6f337":{
      "scriptId":"u26"},
    "a1d5067f5b5c44769ecaa9a5805d667a":{
      "scriptId":"u27"},
    "d246d1c728e142e5b3251ff70b42eef3":{
      "scriptId":"u28"},
    "321ebd89974f49feaa1b5249a9a29e11":{
      "scriptId":"u29"},
    "f04f253e87cc467bbebc7db1dccb9dda":{
      "scriptId":"u30"}}});