$axure.loadCurrentPage({
  "url":"名帖1.html",
  "generationDate":new Date(1467728160166.58),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"6e749573a6184287a77c56dfc5956124",
    "type":"Axure:Page",
    "name":"名帖1",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"83d1e65356df42948331ffd346e73445",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":63,
              "y":0},
            "size":{
              "width":424,
              "height":848},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1360e38edc8e4573bdba77ab848567c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":63,
                  "y":0},
                "size":{
                  "width":424,
                  "height":848},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/名帖1/u0.png"}},
{
          "id":"7725ac1a09a4447c97eef2be178ce449",
          "label":"",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":88,
              "y":89},
            "size":{
              "width":375,
              "height":667}},
          "adaptiveStyles":{
},
          "target":{
            "targetType":"webUrl",
            "urlLiteral":{
              "exprType":"stringLiteral",
              "value":"",
              "stos":[]},
            "includeVariables":false}},
{
          "id":"dd30102e75c94b19b1d60a72598e71f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":194,
              "y":138},
            "size":{
              "width":154,
              "height":154},
            "borderWidth":"4",
            "cornerRadiusTopLeft":"80"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00b0c11e3fc54000ac261ee2b3fd0845",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":194,
                  "y":138},
                "size":{
                  "width":154,
                  "height":154},
                "borderWidth":"4",
                "cornerRadiusTopLeft":"80"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/名帖1/u3.png"}},
{
          "id":"fb35e5ca47ca4900b9f7d853230db30f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":200,
              "y":299},
            "size":{
              "width":145,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c45dbf09a744d72960d4d211e5ec2e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":200,
                  "y":299},
                "size":{
                  "width":145,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d15b9a74d9ad4c4089fb633b63231353",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":110,
              "y":347},
            "size":{
              "width":340,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0cb527c226a4430a82e0ddf59a62d8aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":110,
                  "y":347},
                "size":{
                  "width":340,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d6284ba33bc540849c6597003a8265b7",
          "label":"time_panel",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":88,
              "y":89},
            "size":{
              "width":375,
              "height":20},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2409af430414088a03f8baae47f7065",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":88,
                  "y":89},
                "size":{
                  "width":375,
                  "height":20},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/名帖1/time_panel_u9.png"}},
{
          "id":"dea1978540e843ddb6a05e0c6bdc237a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'IOS8-Icons Regular', 'IOS8-Icons'",
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":126,
              "y":89},
            "size":{
              "width":22,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb08619b814d4a1f8add03fc67e15d39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'IOS8-Icons Regular', 'IOS8-Icons'",
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":126,
                  "y":89},
                "size":{
                  "width":22,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/名帖1/u11.png"}},
{
          "id":"7515ff7211574eeab7d9717cd826d31a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":93,
              "y":97},
            "size":{
              "width":33,
              "height":5}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3612fa2ee62e408da5d2efcdb65230df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":93,
                  "y":97},
                "size":{
                  "width":33,
                  "height":5}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/名帖1/u13.png"}},
{
          "id":"b02eda8e8bcb452d8e605a76dc90974b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":428,
              "y":94},
            "size":{
              "width":25,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e04a5f5472c44747b9353aef28fec718",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":428,
                  "y":94},
                "size":{
                  "width":25,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/名帖1/u15.png"}},
{
          "id":"1dcdd54be0f04f9badfd64af48c9add6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":397,
              "y":91},
            "size":{
              "width":31,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0c959b25ea64ac19589e36daefc2b49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":397,
                  "y":91},
                "size":{
                  "width":31,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/名帖1/u17.png"}},
{
          "id":"22fb1aa8f193472e847fd59bb40aa547",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'IOS8-Icons Regular', 'IOS8-Icons'",
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":375,
              "y":89},
            "size":{
              "width":22,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eddd0cac10064cfb8ce0fe418b9d9f87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'IOS8-Icons Regular', 'IOS8-Icons'",
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":375,
                  "y":89},
                "size":{
                  "width":22,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/名帖1/u11.png"}},
{
          "id":"2d1c1edd4a3f4a35917dabaa7ff1a78d",
          "label":"timer",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":238,
              "y":89},
            "size":{
              "width":18,
              "height":20}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onPanelStateChange":{
              "description":"OnPanelStateChange",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set text on time_panel equal to &quot;[['0'.concat(hours).slice(-...&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["f2409af430414088a03f8baae47f7065"]},
{
                                "exprType":"stringLiteral",
                                "value":"[['0'.concat(hours).slice(-2)]]:[['0'.concat(minutes).slice(-2)]]",
                                "localVariables":{
},
                                "stos":[{
                                    "computedType":"string",
                                    "sto":"fCall",
                                    "thisSTO":{
                                      "computedType":"string",
                                      "desiredType":"string",
                                      "sto":"fCall",
                                      "thisSTO":{
                                        "computedType":"string",
                                        "desiredType":"string",
                                        "sto":"literal",
                                        "value":"0"},
                                      "func":"concat",
                                      "arguments":[{
                                          "sto":"var",
                                          "name":"hours"}]},
                                    "func":"slice",
                                    "arguments":[{
                                        "computedType":"int",
                                        "sto":"unOp",
                                        "op":"-",
                                        "inputSTO":{
                                          "computedType":"int",
                                          "sto":"literal",
                                          "value":2}}]},
{
                                    "computedType":"string",
                                    "sto":"fCall",
                                    "thisSTO":{
                                      "computedType":"string",
                                      "desiredType":"string",
                                      "sto":"fCall",
                                      "thisSTO":{
                                        "computedType":"string",
                                        "desiredType":"string",
                                        "sto":"literal",
                                        "value":"0"},
                                      "func":"concat",
                                      "arguments":[{
                                          "sto":"var",
                                          "name":"minutes"}]},
                                    "func":"slice",
                                    "arguments":[{
                                        "computedType":"int",
                                        "sto":"unOp",
                                        "op":"-",
                                        "inputSTO":{
                                          "computedType":"int",
                                          "sto":"literal",
                                          "value":2}}]}]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]}]}}]}]},
            "onLoad":{
              "description":"OnLoad",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set timer to Next wrap repeat every 60000 ms",
                      "panelsToStates":[{
                          "panelPath":["2d1c1edd4a3f4a35917dabaa7ff1a78d"],
                          "stateInfo":{
                            "setStateType":"next",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":true,
                            "showWhenSet":false,
                            "repeat":60000,
                            "options":{
                              "compress":false}}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"ce9edfa4718e49359470a55e03b2b89b",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"95c3cce217df49e5a2b81e0ae4cb35aa",
              "label":"State2",
              "type":"Axure:PanelDiagram",
              "objects":[],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"57a2976de27b4ffbaed82e4b701559f7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":233,
              "y":697},
            "size":{
              "width":79,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25528b61b847459d8e9a272d58ed4fa1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":233,
                  "y":697},
                "size":{
                  "width":79,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/名帖1/u22.png"}},
{
          "id":"95dbe942e1314e19a1382a7ba6e2421a",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":123,
              "y":424},
            "size":{
              "width":10,
              "height":200},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/pc-页签个人介绍/u98_line.png"}},
{
          "id":"79439dce00714fcd8149f3981908e4ff",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":122,
              "y":436},
            "size":{
              "width":12,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"579d65502e1c4ea9935dff0ec589069a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":122,
                  "y":436},
                "size":{
                  "width":12,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pc-页签个人介绍/u103.png"}},
{
          "id":"b5b57f19c69d4a8aa87691212b55c032",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":122,
              "y":478},
            "size":{
              "width":12,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60476693f20946a097b7093988040571",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":122,
                  "y":478},
                "size":{
                  "width":12,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pc-页签个人介绍/u103.png"}},
{
          "id":"d2271bc51e70498fa2ab6a5ca3ecdae4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":122,
              "y":518},
            "size":{
              "width":12,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce0720c698fd4a06a5197c9fa281f3a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":122,
                  "y":518},
                "size":{
                  "width":12,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pc-页签个人介绍/u103.png"}},
{
          "id":"8d05b678420641bea526dd8026a4dc2e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":122,
              "y":558},
            "size":{
              "width":12,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dec08c0aeb004c1a86b29eb4f6ee4db5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":122,
                  "y":558},
                "size":{
                  "width":12,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pc-页签个人介绍/u103.png"}},
{
          "id":"11a144c253424aea9d5b4f9c396eeace",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":122,
              "y":602},
            "size":{
              "width":12,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c42765f27faf44978f82242d3e5fcf0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":122,
                  "y":602},
                "size":{
                  "width":12,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pc-页签个人介绍/u103.png"}},
{
          "id":"dfe20529bfd146c2acfd82ac00023bcc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":142,
              "y":434},
            "size":{
              "width":102,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21f0ebb07cdb40e1a18741a01a9eea33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":142,
                  "y":434},
                "size":{
                  "width":102,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e2a2fdfb6fda48568c8a8aa5343c7b9b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":142,
              "y":474},
            "size":{
              "width":209,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a09a8b7a3bd54560910f6814193ab9eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":142,
                  "y":474},
                "size":{
                  "width":209,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6014ca5f17f04a3dbdb871b175647dbb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":142,
              "y":516},
            "size":{
              "width":260,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb38f3a8e23c48fb84983518b2578b34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":142,
                  "y":516},
                "size":{
                  "width":260,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5e3c135646034e62955e4a6b501b4a98",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":142,
              "y":556},
            "size":{
              "width":284,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52b6cc084aef4211aa331be92b52a0e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":142,
                  "y":556},
                "size":{
                  "width":284,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fdb3fa8da5d34d398766bbfc18c34030",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":598},
            "size":{
              "width":206,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e78509b12fe347ab9d5bf4be9adc5056",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":598},
                "size":{
                  "width":206,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1988f84b3acc41ee9743f1ca1e2f6e33",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":336,
              "y":242},
            "size":{
              "width":48,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3ea56e6c9eb49e3bf3bfb5e35eaea7d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":336,
                  "y":242},
                "size":{
                  "width":48,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/名帖1/u45.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "83d1e65356df42948331ffd346e73445":{
      "scriptId":"u0"},
    "1360e38edc8e4573bdba77ab848567c4":{
      "scriptId":"u1"},
    "7725ac1a09a4447c97eef2be178ce449":{
      "scriptId":"u2"},
    "dd30102e75c94b19b1d60a72598e71f0":{
      "scriptId":"u3"},
    "00b0c11e3fc54000ac261ee2b3fd0845":{
      "scriptId":"u4"},
    "fb35e5ca47ca4900b9f7d853230db30f":{
      "scriptId":"u5"},
    "2c45dbf09a744d72960d4d211e5ec2e2":{
      "scriptId":"u6"},
    "d15b9a74d9ad4c4089fb633b63231353":{
      "scriptId":"u7"},
    "0cb527c226a4430a82e0ddf59a62d8aa":{
      "scriptId":"u8"},
    "d6284ba33bc540849c6597003a8265b7":{
      "scriptId":"u9"},
    "f2409af430414088a03f8baae47f7065":{
      "scriptId":"u10"},
    "dea1978540e843ddb6a05e0c6bdc237a":{
      "scriptId":"u11"},
    "fb08619b814d4a1f8add03fc67e15d39":{
      "scriptId":"u12"},
    "7515ff7211574eeab7d9717cd826d31a":{
      "scriptId":"u13"},
    "3612fa2ee62e408da5d2efcdb65230df":{
      "scriptId":"u14"},
    "b02eda8e8bcb452d8e605a76dc90974b":{
      "scriptId":"u15"},
    "e04a5f5472c44747b9353aef28fec718":{
      "scriptId":"u16"},
    "1dcdd54be0f04f9badfd64af48c9add6":{
      "scriptId":"u17"},
    "f0c959b25ea64ac19589e36daefc2b49":{
      "scriptId":"u18"},
    "22fb1aa8f193472e847fd59bb40aa547":{
      "scriptId":"u19"},
    "eddd0cac10064cfb8ce0fe418b9d9f87":{
      "scriptId":"u20"},
    "2d1c1edd4a3f4a35917dabaa7ff1a78d":{
      "scriptId":"u21"},
    "57a2976de27b4ffbaed82e4b701559f7":{
      "scriptId":"u22"},
    "25528b61b847459d8e9a272d58ed4fa1":{
      "scriptId":"u23"},
    "95dbe942e1314e19a1382a7ba6e2421a":{
      "scriptId":"u24"},
    "79439dce00714fcd8149f3981908e4ff":{
      "scriptId":"u25"},
    "579d65502e1c4ea9935dff0ec589069a":{
      "scriptId":"u26"},
    "b5b57f19c69d4a8aa87691212b55c032":{
      "scriptId":"u27"},
    "60476693f20946a097b7093988040571":{
      "scriptId":"u28"},
    "d2271bc51e70498fa2ab6a5ca3ecdae4":{
      "scriptId":"u29"},
    "ce0720c698fd4a06a5197c9fa281f3a8":{
      "scriptId":"u30"},
    "8d05b678420641bea526dd8026a4dc2e":{
      "scriptId":"u31"},
    "dec08c0aeb004c1a86b29eb4f6ee4db5":{
      "scriptId":"u32"},
    "11a144c253424aea9d5b4f9c396eeace":{
      "scriptId":"u33"},
    "c42765f27faf44978f82242d3e5fcf0c":{
      "scriptId":"u34"},
    "dfe20529bfd146c2acfd82ac00023bcc":{
      "scriptId":"u35"},
    "21f0ebb07cdb40e1a18741a01a9eea33":{
      "scriptId":"u36"},
    "e2a2fdfb6fda48568c8a8aa5343c7b9b":{
      "scriptId":"u37"},
    "a09a8b7a3bd54560910f6814193ab9eb":{
      "scriptId":"u38"},
    "6014ca5f17f04a3dbdb871b175647dbb":{
      "scriptId":"u39"},
    "eb38f3a8e23c48fb84983518b2578b34":{
      "scriptId":"u40"},
    "5e3c135646034e62955e4a6b501b4a98":{
      "scriptId":"u41"},
    "52b6cc084aef4211aa331be92b52a0e3":{
      "scriptId":"u42"},
    "fdb3fa8da5d34d398766bbfc18c34030":{
      "scriptId":"u43"},
    "e78509b12fe347ab9d5bf4be9adc5056":{
      "scriptId":"u44"},
    "1988f84b3acc41ee9743f1ca1e2f6e33":{
      "scriptId":"u45"},
    "a3ea56e6c9eb49e3bf3bfb5e35eaea7d":{
      "scriptId":"u46"}}});