$axure.loadCurrentPage({
  "url":"搜索结果.html",
  "generationDate":new Date(1467728162859.02),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e9e35691790345e98dc149b559e0a98d",
    "type":"Axure:Page",
    "name":"搜索结果",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"33b1b522ea774a6aa2f5bdc4a53908a7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1366,
              "height":1947}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74370ecc9576411fad05f4071cf83317",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1366,
                  "height":1947}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索结果/u0.png"}},
{
          "id":"4299391f30104b1fba4e9b954af750e4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":777,
              "y":121},
            "size":{
              "width":596,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8244e1764cac47fa9047a2c4b91500b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":777,
                  "y":121},
                "size":{
                  "width":596,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索结果/u2.png"}},
{
          "id":"7e668538c1b94ae29cb48a518d3d1065",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1110,
              "y":128},
            "size":{
              "width":50,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c827739795004fc495e6b4ef14dd0339",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1110,
                  "y":128},
                "size":{
                  "width":50,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索结果/u4.png"}},
{
          "id":"bfc386995cc6486b82501640b65d4791",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":777,
              "y":227},
            "size":{
              "width":403,
              "height":339},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22abf7757df549c499eb0a3c55405863",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":777,
                  "y":227},
                "size":{
                  "width":403,
                  "height":339},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索结果/u6.png"}},
{
          "id":"6035139ff5e64b86bc77886726ed0405",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":784,
              "y":241},
            "size":{
              "width":85,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c07c15dc16e4fbd9e1787bb124831a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":784,
                  "y":241},
                "size":{
                  "width":85,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e314087a277d473eb82f2f61303e9463",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":802,
              "y":280},
            "size":{
              "width":71,
              "height":75}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f03dfb61b9714610a6c0c9b754b56998",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":802,
                  "y":280},
                "size":{
                  "width":71,
                  "height":75}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索结果/u10.png"}},
{
          "id":"4a8dad2a5eeb448eb26e01377abc06d7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":782,
              "y":345},
            "size":{
              "width":135,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c303b7145f7a4ca58cebe05e3ef762bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":782,
                  "y":345},
                "size":{
                  "width":135,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索结果/u12.png"}},
{
          "id":"7651c45e1e4040a48c394c7f00c11ef6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":936,
              "y":281},
            "size":{
              "width":71,
              "height":75}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61d70cb54c6a4cd4ace1b86c594b5fd6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":936,
                  "y":281},
                "size":{
                  "width":71,
                  "height":75}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索结果/u10.png"}},
{
          "id":"58213993878f444cb2fa7ced9550cb42",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":911,
              "y":346},
            "size":{
              "width":135,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2a9b5c82f7f4441961ba2a37652f8e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":911,
                  "y":346},
                "size":{
                  "width":135,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索结果/u12.png"}},
{
          "id":"bd356c8041d04889948fde309cbaa402",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1068,
              "y":281},
            "size":{
              "width":71,
              "height":75}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"559061b2a87147038752bdaec0ef9bd7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1068,
                  "y":281},
                "size":{
                  "width":71,
                  "height":75}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索结果/u10.png"}},
{
          "id":"a984ab2edda643d5b6bd86dc96b688b7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1041,
              "y":346},
            "size":{
              "width":135,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c370bedefef40b5b2b76b9addf33a92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1041,
                  "y":346},
                "size":{
                  "width":135,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索结果/u12.png"}},
{
          "id":"cbbc0eb90532465599f97dc870cd5a78",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":783,
              "y":401},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5928b970a574ccc9c615f85c9416a69",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":783,
                  "y":401},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"706d6f261bb64802a3efab0e34005d5e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":749,
              "y":540},
            "size":{
              "width":265,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6725eba895f4577ae202593bd1a9f7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":749,
                  "y":540},
                "size":{
                  "width":265,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索结果/u24.png"}},
{
          "id":"c3a435f943ed40d489847e5af647eadc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000CC,
              "opacity":1},
            "location":{
              "x":785,
              "y":584},
            "size":{
              "width":234,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3004627a9a1b4ecfa62f571e917f6834",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000CC,
                  "opacity":1},
                "location":{
                  "x":785,
                  "y":584},
                "size":{
                  "width":234,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f784dbb0986144e8b56c04d5376ea3c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":845,
              "y":177},
            "size":{
              "width":315,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"439336a14c614aaa9f946ac07ff9de7b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":845,
                  "y":177},
                "size":{
                  "width":315,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索结果/u28.png"}},
{
          "id":"ff74feaebd9e473bb36801057944d4b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":845,
              "y":199},
            "size":{
              "width":315,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af9a358ba158476aa4a575c3a6e40473",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":845,
                  "y":199},
                "size":{
                  "width":315,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索结果/u28.png"}},
{
          "id":"669d6d1adae6490fa0272a75f7d29699",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1180,
              "y":121},
            "size":{
              "width":322,
              "height":253}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1fee442b5ce40fd89e369c43269aa75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1180,
                  "y":121},
                "size":{
                  "width":322,
                  "height":253}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索结果/u32.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "33b1b522ea774a6aa2f5bdc4a53908a7":{
      "scriptId":"u0"},
    "74370ecc9576411fad05f4071cf83317":{
      "scriptId":"u1"},
    "4299391f30104b1fba4e9b954af750e4":{
      "scriptId":"u2"},
    "8244e1764cac47fa9047a2c4b91500b9":{
      "scriptId":"u3"},
    "7e668538c1b94ae29cb48a518d3d1065":{
      "scriptId":"u4"},
    "c827739795004fc495e6b4ef14dd0339":{
      "scriptId":"u5"},
    "bfc386995cc6486b82501640b65d4791":{
      "scriptId":"u6"},
    "22abf7757df549c499eb0a3c55405863":{
      "scriptId":"u7"},
    "6035139ff5e64b86bc77886726ed0405":{
      "scriptId":"u8"},
    "8c07c15dc16e4fbd9e1787bb124831a8":{
      "scriptId":"u9"},
    "e314087a277d473eb82f2f61303e9463":{
      "scriptId":"u10"},
    "f03dfb61b9714610a6c0c9b754b56998":{
      "scriptId":"u11"},
    "4a8dad2a5eeb448eb26e01377abc06d7":{
      "scriptId":"u12"},
    "c303b7145f7a4ca58cebe05e3ef762bd":{
      "scriptId":"u13"},
    "7651c45e1e4040a48c394c7f00c11ef6":{
      "scriptId":"u14"},
    "61d70cb54c6a4cd4ace1b86c594b5fd6":{
      "scriptId":"u15"},
    "58213993878f444cb2fa7ced9550cb42":{
      "scriptId":"u16"},
    "a2a9b5c82f7f4441961ba2a37652f8e7":{
      "scriptId":"u17"},
    "bd356c8041d04889948fde309cbaa402":{
      "scriptId":"u18"},
    "559061b2a87147038752bdaec0ef9bd7":{
      "scriptId":"u19"},
    "a984ab2edda643d5b6bd86dc96b688b7":{
      "scriptId":"u20"},
    "2c370bedefef40b5b2b76b9addf33a92":{
      "scriptId":"u21"},
    "cbbc0eb90532465599f97dc870cd5a78":{
      "scriptId":"u22"},
    "d5928b970a574ccc9c615f85c9416a69":{
      "scriptId":"u23"},
    "706d6f261bb64802a3efab0e34005d5e":{
      "scriptId":"u24"},
    "c6725eba895f4577ae202593bd1a9f7f":{
      "scriptId":"u25"},
    "c3a435f943ed40d489847e5af647eadc":{
      "scriptId":"u26"},
    "3004627a9a1b4ecfa62f571e917f6834":{
      "scriptId":"u27"},
    "f784dbb0986144e8b56c04d5376ea3c9":{
      "scriptId":"u28"},
    "439336a14c614aaa9f946ac07ff9de7b":{
      "scriptId":"u29"},
    "ff74feaebd9e473bb36801057944d4b6":{
      "scriptId":"u30"},
    "af9a358ba158476aa4a575c3a6e40473":{
      "scriptId":"u31"},
    "669d6d1adae6490fa0272a75f7d29699":{
      "scriptId":"u32"},
    "c1fee442b5ce40fd89e369c43269aa75":{
      "scriptId":"u33"}}});